apiVersion: 1

deleteDatasources:
  - name: prometheus
    orgId: 1

datasources:
  - name: Mimir
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
